### ISSUE TITLE
Queue for transfer is broken when I use internal links

### ISSUE THREAD

**Issue by stefantectu** [umbraco/Umbraco.Heartcore.Issues#128]
### Summary

We try to sync the content from dev to staging and we get the following error:

```
An error occurred
The source environment has thrown a Newtonsoft.Json.JsonReaderException with message: Error parsing undefined value. Path '', line 1, position 1.
The technical details may contain more information.

640dd948 - Executing, 20% - Create manifest on source
640dd948 - Executing, 25% - Review manifest on target
❤
640dd948 - Executing, 25% - Update manifest on source
640dd948 - Executing, 80% - Exception!
640dd948 - Executing, 80% - Abort remote session
640dd948 - Failed, 80% - Total time 00:00:05.185.

-- EXCEPTION ---------------------------------------------------
 (proper exception traces at the end of this log)
Newtonsoft.Json.JsonReaderException: Error parsing undefined value. Path '', line 1, position 1.
----------------------------------------------------------------

EXCEPTION:

Newtonsoft.Json.JsonReaderException: Error parsing undefined value. Path '', line 1, position 1.
   at Newtonsoft.Json.JsonTextReader.ParseUndefined()
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Linq.JToken.ReadFrom(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JToken.Parse(String json, JsonLoadSettings settings)
   at Umbraco.Deploy.Contrib.Connectors.ValueConnectors.MultiUrlPickerValueConnector.ToArtifact(Object value, PropertyType propertyType, ICollection`1 dependencies, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.SerializeNonVariantValue(ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, Property property, IValueConnector valueConnector, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.AddProperty(Property property, ICollection`1 dependencies, Boolean published, IDictionary`2 propertyCollection, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.ContentConnectorBase`2.MapArtifactProperties(PropertyCollection properties, ICollection`1 dependencies, Boolean published, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnectorBase.MapVersion(IContent content, ICollection`1 dependencies, Boolean published, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContent content, IContextCache contextCache)
   at Umbraco.Deploy.Connectors.ServiceConnectors.ContentConnector.DocumentConnector.GetArtifact(GuidUdi udi, IContextCache contextCache)
   at Umbraco.Deploy.Environments.CurrentEnvironment.GetDependencyArtifact(ArtifactDependency dep, DependentArtifactState& dependentArtifactState, String& dependencyName, String& dependencyErrorMessage, IContextCache contextCache)
   at Umbraco.Deploy.Environments.CurrentEnvironment.AddEntries(Manifest manifest, List`1 sigs, IEnumerable`1 items, HashSet`1 exclude, IWorkItem workItem, CancellationToken token)
   at Umbraco.Deploy.Environments.CurrentEnvironment.UpdateManifest(Guid sessionId, Manifest manifest, IEnumerable`1 exclude)
   at Umbraco.Deploy.Environments.CurrentEnvironment.UpdateManifestAsync(Guid sessionId, Manifest manifest, IEnumerable`1 exclude, CancellationToken token)
   at Umbraco.Deploy.Work.WorkItems.DeployRestoreWorkItemBase.<NegotiateManifest>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ProceedToPackage>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsyncSub>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteForItems>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Umbraco.Deploy.Work.WorkItems.SourceDeployWorkItem.<ExecuteAsync>d__21.MoveNext()
```

This happens only for the node that contain internal links:

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/14b4a719-be8d-4512-9caa-6516c8b87699)
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/d25f37c4-dfb6-432b-ac4a-d5d411f615a6)

It is reproducible for all Document Types that contain Url Pickers with internal link, if we put external links it's working fine.

### Steps to reproduce

1. Create a simple Document Type.

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/7551ab30-796f-47e2-82fc-9f89f6f2ae37)

**_to_** should be a new Url picker:

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/164bf99f-80f7-4c2c-a62d-ea5659eb76a2)

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/a73ba33b-99b7-47ff-a811-50e0b2ffa800)

2. Create a content Node with this document Type:

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/e11e4348-a61b-49b3-a4e8-394040b652a3)

Add an internal link on the url field.

3. Queue for Transfer
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/e2866dbf-7e27-47e8-98c7-221718ce48a4)

![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/99821df2-a54d-44a9-8642-7151d3914cd8)

4. Check the error
![image](https://github.com/umbraco/Umbraco.Heartcore.Issues/assets/125254670/fce1141b-3ceb-41a9-b5d3-33cf3cf81f29)

**Comment by AndyButland** [comment]
Just to add a comment from the Umbraco Deploy side of things - which is where this exception is coming from.  I've tested both internal and external links for the multi URL picker on the latest version of Deploy for the CMS version running on Heartcore, and I'm not seeing this issue.

**Comment by jmf-umbraco** [comment]
Thanks @stefantectu for raising this, and thanks for confirming our suspicions @AndyButland. I have confirmed that this issue is no longer present in our latest build, which we will roll out for new Heartcore projects in the next few weeks.

Unfortunately that upgrade is quite significant under the hood and thus rolling it out for existing sites is a somewhat larger undertaking. We anticipate that this fix will be available for existing sites later in Q1 of this year, but if this is a blocker then we may be able to deal with sites on a case-by-case basis through support.

**Comment by jmf-umbraco** [comment]
We've just rolled out a version of Heartcore that fixes this issue for all sites created after 12th February 2024. Existing sites will have this rolled out in Q2 this year.

If you require an urgent fix for this, then please reach out and create a support ticket and they should be able to apply the necessary update to your site ahead of that schedule!
